/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditTrailRouteImport } from './routes/audit-trail'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as RecoveryCenterRouteImport } from './routes/recovery-center'
import { Route as RevenueRiskRouteImport } from './routes/revenue-risk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TransactionsTransactionIdRouteImport } from './routes/transactions.$transactionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditTrailRoute = AuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryCenterRoute = RecoveryCenterRouteImport.update({
  id: '/recovery-center',
  path: '/recovery-center',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRiskRoute = RevenueRiskRouteImport.update({
  id: '/revenue-risk',
  path: '/revenue-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsTransactionIdRoute =
  TransactionsTransactionIdRouteImport.update({
    id: '/transactions/$transactionId',
    path: '/transactions/$transactionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/demo': typeof DemoRoute
  '/insights': typeof InsightsRoute
  '/recovery-center': typeof RecoveryCenterRoute
  '/revenue-risk': typeof RevenueRiskRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/demo': typeof DemoRoute
  '/insights': typeof InsightsRoute
  '/recovery-center': typeof RecoveryCenterRoute
  '/revenue-risk': typeof RevenueRiskRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-trail': typeof AuditTrailRoute
  '/demo': typeof DemoRoute
  '/insights': typeof InsightsRoute
  '/recovery-center': typeof RecoveryCenterRoute
  '/revenue-risk': typeof RevenueRiskRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/transactions/$transactionId': typeof TransactionsTransactionIdRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-trail'
    | '/demo'
    | '/insights'
    | '/recovery-center'
    | '/revenue-risk'
    | '/settings'
    | '/simulator'
    | '/transactions/$transactionId'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-trail'
    | '/demo'
    | '/insights'
    | '/recovery-center'
    | '/revenue-risk'
    | '/settings'
    | '/simulator'
    | '/transactions/$transactionId'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/audit-trail'
    | '/demo'
    | '/insights'
    | '/recovery-center'
    | '/revenue-risk'
    | '/settings'
    | '/simulator'
    | '/transactions/$transactionId'
    | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditTrailRoute: typeof AuditTrailRoute
  DemoRoute: typeof DemoRoute
  InsightsRoute: typeof InsightsRoute
  RecoveryCenterRoute: typeof RecoveryCenterRoute
  RevenueRiskRoute: typeof RevenueRiskRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  TransactionsTransactionIdRoute: typeof TransactionsTransactionIdRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-trail': {
      id: '/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AuditTrailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-center': {
      id: '/recovery-center'
      path: '/recovery-center'
      fullPath: '/recovery-center'
      preLoaderRoute: typeof RecoveryCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue-risk': {
      id: '/revenue-risk'
      path: '/revenue-risk'
      fullPath: '/revenue-risk'
      preLoaderRoute: typeof RevenueRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$transactionId': {
      id: '/transactions/$transactionId'
      path: '/transactions/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof TransactionsTransactionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditTrailRoute: AuditTrailRoute,
  DemoRoute: DemoRoute,
  InsightsRoute: InsightsRoute,
  RecoveryCenterRoute: RecoveryCenterRoute,
  RevenueRiskRoute: RevenueRiskRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  TransactionsTransactionIdRoute: TransactionsTransactionIdRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
